tasks:
  - name: Backend
    init: |
      cd server
      npm install
    command: npm run dev
    env:
      SESSION_SECRET: oiwnewerJlw70238974
      DATABASE_URL: postgres://localhost/postgres
  - name: Frontend
    init: |
      cd client
      npm install
    command: npm start
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: notify
    visibility: public
